2024-11-20 18:31:20.623 | ERROR    | utils.loggings:exception:40 - list index out of range
Traceback (most recent call last):

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000022D8AFDE040>
    └ <Thread(Thread-7, started daemon 37276)>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000022D8AFDDD30>
    └ <Thread(Thread-7, started daemon 37276)>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-7, started daemon 37276)>
    │    │        │    └ (<socket.socket fd=1196, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr...
    │    │        └ <Thread(Thread-7, started daemon 37276)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x0000022D8EE27A00>>
    └ <Thread(Thread-7, started daemon 37276)>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56730)
    │    │              └ <socket.socket fd=1196, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.finish_request at 0x0000022D8AFE0940>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x0000022D8EE27A00>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x0000022D8EE27A00>
    │    │                   │        └ ('127.0.0.1', 56730)
    │    │                   └ <socket.socket fd=1196, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x0000022D8EE27A00>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000022D8CDA4820>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000022D90D9EDC0>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\http\server.py", line 435, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000022D8CBADCA0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000022D90D9EDC0>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\http\server.py", line 423, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x0000022D90D9EDC0>>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'app'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x0000022D8EE27A00>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x0000022D90D9EDC0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x0000022D90D73E50>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000022D90D73AF0>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1196>, 'wsgi.errors': <_io.TextIOW...
                       └ <Flask 'app'>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000022D90D73AF0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1196>, 'wsgi.errors': <_io.TextIOW...
           │    └ <function Flask.wsgi_app at 0x0000022D8D6C8280>
           └ <Flask 'app'>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x0000022D8D6C6A60>
               └ <Flask 'app'>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x0000022D8D6C69D0>
         └ <Flask 'app'>

  File "C:\Users\15201\.conda\envs\ai-chatbot\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {'ConversationID': 198509445}
           │    │           │    │              │    └ 'message.getHistoryMessage'
           │    │           │    │              └ <Rule '/api_1_0/message/getHistoryMessage/<ConversationID>' (GET, OPTIONS, HEAD) -> message.getHistoryMessage>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x0000022D8EC1F4C0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x0000022D8D6C6C10>
           └ <Flask 'app'>

  File "D:\cityu课件\DataEngineering\Project\AI-chatbot\Backend\api_1_0\messageResource\urls.py", line 20, in getHistoryMessage
    return MessageOtherResource.getHistoryMessage(ConversationID=ConversationID)
           │                    │                                └ 198509445
           │                    └ <classmethod object at 0x0000022D90A65E20>
           └ <class 'api_1_0.messageResource.messageOtherResource.MessageOtherResource'>

  File "D:\cityu课件\DataEngineering\Project\AI-chatbot\Backend\api_1_0\messageResource\messageOtherResource.py", line 82, in getHistoryMessage
    title = ConversationService.get_title(ConversationID=ConversationID)['data']
            │                   │                        └ 198509445
            │                   └ <classmethod object at 0x0000022D8EF2A760>
            └ <class 'service.conversationService.ConversationService'>

> File "D:\cityu课件\DataEngineering\Project\AI-chatbot\Backend\service\conversationService.py", line 43, in get_title
    res=results['data'][0]['Title']
        └ {'code': '2000', 'message': 'successfully!', 'totalCount': 0, 'totalPage': 0, 'data': []}

IndexError: list index out of range
